version: '3'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile 
    env_file: 
      - .env
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - api-node_modules:/usr/src/app/node_modules
    depends_on: 
      - postgres

  postgres:
    image: "postgres:12.3"
    ports:
      - "5432:5432"
    env_file: 
      - .env
    environment:
      POSTGRES_USER: ${TYPEORM_USERNAME}
      POSTGRES_PASSWORD: ${TYPEORM_PASSWORD}
      POSTGRES_DB: ${TYPEORM_DATABASE}
    volumes:
      - padgea-db:/var/lib/postgresql/data

volumes:
  padgea-db:
  api-node_modules: